sudo: required
services:
  - docker

before_install:
  - docker build -t csandynguyen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csandynguyen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-590183857532"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  access_key_id: "$AWS_SECRET_KEY"

